apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: wechat-notification
    spec:
      containers:
      - name: wechat-notification
        image: curlimages/curl
        command:
          - "curl"
          - "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=580c8ae2-f406-4509-ab75-7a506cb84887"
          - "-H"
          - "Content-Type: application/json"
          - "-d"
          - "{\"msgtype\": \"text\",\"text\": {\"content\": \"postSync\"}}"
      restartPolicy: Never
  backoffLimit: 2

