apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    recipients.argocd-notifications.argoproj.io: webhook:wechatrobot
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: IfNotPresent
