apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginx
        name: guestbook-ui1113
        command: ["echo", "$(for i in {1..10};do curl baidu.com;done)"]
        ports:
        - containerPort: 80
