apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      restart_policy: OnFailure
      containers:
      - image: busybox
        name: busybox
        imagePullPolicy: IfNotPresent
        command: ["sleep","10","echo", "testcontent"]
